Profile and Edit Page
eilenshahbaz/LEAD-Center pull request #16
Opened 2019-04-12 06:12 UTC by tonyli537

Created the Profile and Edit page for user

2019-04-12 07:15 UTC, melvinhernandez requested changes
Some blockers before merging to master: 

This is good to show to the client as a possible prototype for profile edit, but I think we also need to implement the whole profile creation logic. Biggest thing we need to consider is that from my understanding the profile edit page actions should be part of the User controller and not its own controller. We also need to add tests to the pages before merging. 

I would wait and create the User model through devise, since they usually give us the scaffolded layout and forms, but this is for sure useful when we implement it through devise. 👍

2019-04-12 07:15 UTC, melvinhernandez commented on app/views/profile/edit.html.erb
> +<!DOCTYPE html>
We should get rid of lines `1-13` since that's already being added by the default layout  👍

2019-04-12 07:15 UTC, melvinhernandez commented on app/views/profile/edit.html.erb
> +                <input class="form-check-input" type="checkbox" id="graduate" name="graduate">
There's a simpler way of checking the checkbox without the JavaScript, by doing 😄 
`<input class="form-check-input" type="checkbox" id="transfer" name="transfer" <%= 'checked' unless !@profile.transfer %>>`

This will just add the `checked` attribute by default to the checkboxes unless they're false in the profile! Do the same for the graduate and the international checkboxes 👍

2019-04-12 07:15 UTC, melvinhernandez commented on app/views/profile/show.html.erb
> +<!DOCTYPE html>
Same as before, remove lines '1-13`

2019-04-12 07:15 UTC, melvinhernandez commented on app/controllers/profile_controller.rb
> +  def update
We should strongly consider using strong params when we're updating the profile, [documentation here](https://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters)

2019-04-15 22:52 UTC, melvinhernandez requested changes

2019-04-15 22:52 UTC, melvinhernandez commented on app/controllers/profile_controller.rb
> +      params.permit(:first_name, :last_name, :major, :gender, :grad_year, :ethnicity, :transfer, :graduate, :international)
Nice 👍

2019-04-15 22:52 UTC, melvinhernandez commented on app/views/profile/edit.html.erb
> +<!DOCTYPE html>
We don't need lines `1-8`, so everything above the `nav` tag

2019-04-15 22:52 UTC, melvinhernandez commented on app/views/profile/edit.html.erb
> +<!DOCTYPE html>
TODO: In the next iteration, we should also consider consolidating the nav as its own partial or just add it to the layout so we don't have to put it in every page.

2019-04-15 22:52 UTC, melvinhernandez commented on app/views/profile/show.html.erb
> +<!DOCTYPE html>
Same as before, remove lines above the `nav` bar.

2019-04-15 22:52 UTC, melvinhernandez commented on app/views/profile/show.html.erb
> +        <script type="text/javascript">
We can potentially do this without JavaScript and just do it with just embedded ruby, how about writing `<%= @profile.transfer ? 'Yes' : 'No' %>` inside the `<span class="transfer" id='transfer'></span>` tags. Same for graduate and international 🙌🏾

2019-04-15 23:19 UTC, Hekaiyo commented
It appears that since Juan's branch was merged, your test step definitions are conflicting with his.

2019-04-16 04:05 UTC, Hekaiyo requested changes
Otherwise looks good

2019-04-16 04:05 UTC, Hekaiyo commented on config/routes.rb
> +  get 'profile/:id'=> 'profile#show', :as => 'show'
Should probably rename this and the next one to "show_profile" and "edit_profile" to prevent ambiguity and future issues.

2019-04-16 04:05 UTC, Hekaiyo commented on config/routes.rb
> +  post 'profile/:id/edit' => 'profile#edit', :as => 'edit_profile'
This path (POST to profile/:id/edit) seems to never be used, should remove.

2019-04-16 04:05 UTC, Hekaiyo commented on config/routes.rb
> +  get 'profile/:id'=> 'profile#show', :as => 'show'
Don't forget to update usages of these path aliases in your profile_controller.rb!

2019-04-16 04:24 UTC, Hekaiyo approved these changes

2019-04-16 04:33 UTC, merged