Eilen/omniauth ets
eilenshahbaz/LEAD-Center pull request #20
Opened 2019-04-21 04:41 UTC by eilenshahbaz

Per ETS:
```Hi Eilen,

Thanks for registering your URL pattern(s). These are now authorized for the CAS Servers auth-test.b.e and auth.b.e as noted below.

CAS authZ is enabled for your service as follows:

Students, and members of the edu:berkeley:app:auth-cas:communities_at_cal:communities_at_cal-allow
```
I'm assuming auth-test.b.e and auth.b.e refer to the servers specified here: https://calnetweb.berkeley.edu/calnet-technologists/cas/casifying-your-web-application-or-web-server/first-level-cas-service-urls

Unable to play with it locally since these servers don't recognize localhost as a registered client/provider.

2019-05-10 03:31 UTC, kaandogusoy commented on app/controllers/sessions_controller.rb
> -  def signout
not sure why you changed the name, does it change the way it works

2019-05-10 03:31 UTC, kaandogusoy commented on spec/controllers/sessions_controller_spec.rb
> +require 'rails_helper'
looks good I might add another test for sad path later tonight

2019-05-11 23:42 UTC, melvinhernandez requested changes
The authentication and tests look pretty good! 🤙
Only blockers before merging are:
- [x] Add test for `failure` method in `sessions_controller.rb` to get it to 100%.
- [x] Resolve merge conflicts with master branch for `Gemfile` and `schema.rb`.

2019-05-11 23:42 UTC, melvinhernandez commented on app/views/placeholder/landing.html.erb
> +                   style="background: linear-gradient(#2683bc, #1f7099), #1f7099"/>
Ideally we should not do inline style to help with maintainability, but not a blocker for this feature!

2019-05-11 23:42 UTC, melvinhernandez commented on app/controllers/sessions_controller.rb
> +    session[:logged_in] = false
Looks like this method is not being tested, so just add one more test for this to get it to 100% 👍

2019-05-12 07:27 UTC, melvinhernandez approved these changes

2019-05-12 07:27 UTC, merged